// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicSocialNetwork.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicSocialNetwork.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230310235746_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlbumMusician", b =>
                {
                    b.Property<int>("AlbumsId")
                        .HasColumnType("integer");

                    b.Property<int>("MusiciansId")
                        .HasColumnType("integer");

                    b.HasKey("AlbumsId", "MusiciansId");

                    b.HasIndex("MusiciansId");

                    b.ToTable("AlbumMusician");
                });

            modelBuilder.Entity("AlbumPerson", b =>
                {
                    b.Property<int>("AddedAlbumsId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonsId")
                        .HasColumnType("integer");

                    b.HasKey("AddedAlbumsId", "PersonsId");

                    b.HasIndex("PersonsId");

                    b.ToTable("AlbumPerson");
                });

            modelBuilder.Entity("MusicianTrack", b =>
                {
                    b.Property<int>("MusiciansId")
                        .HasColumnType("integer");

                    b.Property<int>("TracksId")
                        .HasColumnType("integer");

                    b.HasKey("MusiciansId", "TracksId");

                    b.HasIndex("TracksId");

                    b.ToTable("MusicianTrack");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.AddedPlaylists", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("AddedPlaylists");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.AddedTracks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TrackId");

                    b.ToTable("AddedTracks");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlbumTitle")
                        .HasColumnType("text")
                        .HasColumnName("album_title");

                    b.Property<int>("AuditionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("auditions_count");

                    b.Property<byte[]>("Cover")
                        .HasColumnType("bytea")
                        .HasColumnName("cover");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("genre");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.ListenPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TrackId");

                    b.ToTable("ListenPerson");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Musician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Musicians");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("Login");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.PlaylistTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("playlistId")
                        .HasColumnType("integer");

                    b.Property<int>("trackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("playlistId");

                    b.HasIndex("trackId");

                    b.ToTable("PlaylistTrack");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Publications", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("MusicianId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicationsPhoto")
                        .HasColumnType("text")
                        .HasColumnName("PublicationsPhoto");

                    b.Property<string>("PublicationsText")
                        .HasColumnType("text")
                        .HasColumnName("PublicationsText");

                    b.HasKey("id");

                    b.HasIndex("MusicianId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "User"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Admin"
                        });
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Subscriptions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MusicianId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("id");

                    b.HasIndex("MusicianId");

                    b.HasIndex("PersonId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("AlbumMusician", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSocialNetwork.Entities.Musician", null)
                        .WithMany()
                        .HasForeignKey("MusiciansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlbumPerson", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Album", null)
                        .WithMany()
                        .HasForeignKey("AddedAlbumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSocialNetwork.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicianTrack", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Musician", null)
                        .WithMany()
                        .HasForeignKey("MusiciansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSocialNetwork.Entities.Track", null)
                        .WithMany()
                        .HasForeignKey("TracksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.AddedPlaylists", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Person", "Person")
                        .WithMany("MyPlaylists")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSocialNetwork.Entities.Playlist", "Playlist")
                        .WithMany("AddedPlaylists")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.AddedTracks", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Person", "Person")
                        .WithMany("MyTracks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSocialNetwork.Entities.Track", "Track")
                        .WithMany("PersonAddedTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Album", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Genre", "Genre")
                        .WithMany("Albums")
                        .HasForeignKey("GenreId");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.ListenPerson", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Person", "Person")
                        .WithMany("ListenPerson")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSocialNetwork.Entities.Track", "Track")
                        .WithMany("ListenPerson")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Musician", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Person", "Person")
                        .WithMany("Musicians")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Person", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Playlist", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Person", "Person")
                        .WithMany("Playlists")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.PlaylistTrack", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Playlist", "playlist")
                        .WithMany("TrackAddedPlaylist")
                        .HasForeignKey("playlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSocialNetwork.Entities.Track", "track")
                        .WithMany("PlaylistAddedTracks")
                        .HasForeignKey("trackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("playlist");

                    b.Navigation("track");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Publications", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Musician", "Musician")
                        .WithMany("PublicationsList")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Subscriptions", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Musician", "Musician")
                        .WithMany("Subscribers")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSocialNetwork.Entities.Person", "Person")
                        .WithMany("SubscribeMusician")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Track", b =>
                {
                    b.HasOne("MusicSocialNetwork.Entities.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Genre", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Musician", b =>
                {
                    b.Navigation("PublicationsList");

                    b.Navigation("Subscribers");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Person", b =>
                {
                    b.Navigation("ListenPerson");

                    b.Navigation("Musicians");

                    b.Navigation("MyPlaylists");

                    b.Navigation("MyTracks");

                    b.Navigation("Playlists");

                    b.Navigation("SubscribeMusician");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Playlist", b =>
                {
                    b.Navigation("AddedPlaylists");

                    b.Navigation("TrackAddedPlaylist");
                });

            modelBuilder.Entity("MusicSocialNetwork.Entities.Track", b =>
                {
                    b.Navigation("ListenPerson");

                    b.Navigation("PersonAddedTracks");

                    b.Navigation("PlaylistAddedTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
